In [18]:
import pandas as pd


def process_peptide(sentence: str) -> str:
    """
    Process Peptide string and output start and end points
    for a given peptide
    """
    frags = sentence.split(";")
    frags = [f.replace("PEPTIDE ", "").replace("..", "-")
             for f in frags if "PEPTIDE" in f]
    return ";".join(frags)


df = pd.read_csv("../data/swissprot-peptide.tsv", sep='\t')
df = df[['Entry', "Organism", "Length", "Peptide", "Sequence"]]

df["Peptide"] = df["Peptide"].map(process_peptide)
df.to_csv("../processed-data/peptide.tsv", sep='\t', index=False)

In [19]:
df

,Entry,Organism,Length,Peptide,Sequence
0,A0A024B7W1,Zika virus (isolate ZIKV/Human/French Polynesi...,3423,2247-2269,MKNPKKKSGGFRIVNMLKRGVARVSPFGGLKRLPAGLLLGHGPIRM...
1,A0A068B6Q6,Conus betulinus (Beech cone),37,21-36,PDGRNAAAKAFDLITPTVRKGCCSNPACILNNPNQCG
2,A0A088MIT0,Physalaemus nattereri (Cuyaba dwarf frog) (Eup...,134,47-56; 59-70; 85-96; 124-134; 124-132; 124-131,MAFLKKSLFLVLFLGVVSLSFCEEEKREEHEEEKRDEEDAESLGKR...
3,A0A0A1I6E7,Androctonus crassicauda (Arabian fat-tailed sc...,74,23-40,MEIKYLLTVFLVLLIVSDHCQAFLFSLIPHAISGLISAFKGRRKRD...
4,A0A0A1I6N9,Androctonus crassicauda (Arabian fat-tailed sc...,74,23-40,MEIKYLLTVFLVLLIVSDHCQAFLFSLIPNAISGLLSAFKGRRKRN...
...,...,...,...,...,...
8905,Q8Z5K2,Salmonella typhi,13,1-13,MTRVQFKHHHHPD
8906,Q8Z9H9,Salmonella typhi,28,1-28,MSYIVRFTGLLLLNAFIVRGRPVGGIQH
8907,Q9BP49,Conus tessulatus (Tessellate cone),20,<1-20,NNPPCCSGYVCEGVYCAVDV
8908,Q9NRI7,Homo sapiens (Human),21,1-21,MAAACRCLSLLLLSTCVALLL
8909,Q9U5V6,Drosophila melanogaster (Fruit fly),39,1-39,MWAAKLIVVTLLLLQFAALALSCSCGEEAKLECGCTKHH

In [ ]:

df['Peptides'] = peptides
df['Sites'] = sites
print(f"Num of proteins without sites: {len(df[df['Sites'].map(len) < 1]):,}")
df = df[df['Sites'].map(len) > 0].copy()
df


# df['Sites'] = df['Sites'].map(lambda x: [(int(e.split('-'))[0]-1, int(e.split('-'))[1]+1) for e in x])
# df

Num of proteins without sites: 219

,Entry,Organism,Length,Peptide,Sequence,Sites,Peptides
0,A0A024B7W1,Zika virus (isolate ZIKV/Human/French Polynesi...,3423,2247-2269,MKNPKKKSGGFRIVNMLKRGVARVSPFGGLKRLPAGLLLGHGPIRM...,[2246],"[(2247, 2269)]"
1,A0A068B6Q6,Conus betulinus (Beech cone),37,21-36,PDGRNAAAKAFDLITPTVRKGCCSNPACILNNPNQCG,[20],"[(21, 36)]"
2,A0A088MIT0,Physalaemus nattereri (Cuyaba dwarf frog) (Eup...,134,47-56; 59-70; 85-96; 124-134; 124-132; 124-131,MAFLKKSLFLVLFLGVVSLSFCEEEKREEHEEEKRDEEDAESLGKR...,"[46, 58, 84, 123, 135, 123, 123]","[(47, 56), (59, 70), (85, 96), (124, 134), (12..."
3,A0A0A1I6E7,Androctonus crassicauda (Arabian fat-tailed sc...,74,23-40,MEIKYLLTVFLVLLIVSDHCQAFLFSLIPHAISGLISAFKGRRKRD...,[22],"[(23, 40)]"
4,A0A0A1I6N9,Androctonus crassicauda (Arabian fat-tailed sc...,74,23-40,MEIKYLLTVFLVLLIVSDHCQAFLFSLIPNAISGLLSAFKGRRKRN...,[22],"[(23, 40)]"
...,...,...,...,...,...,...,...
8904,Q8XAT0,Escherichia coli O157:H7,33,1-33,MRSEQISGSSLNPSCRFSSAYSPVTRQRKDMSR,[34],"[(1, 33)]"
8905,Q8Z5K2,Salmonella typhi,13,1-13,MTRVQFKHHHHPD,[14],"[(1, 13)]"
8906,Q8Z9H9,Salmonella typhi,28,1-28,MSYIVRFTGLLLLNAFIVRGRPVGGIQH,[29],"[(1, 28)]"
8908,Q9NRI7,Homo sapiens (Human),21,1-21,MAAACRCLSLLLLSTCVALLL,[22],"[(1, 21)]"
8909,Q9U5V6,Drosophila melanogaster (Fruit fly),39,1-39,MWAAKLIVVTLLLLQFAALALSCSCGEEAKLECGCTKHH,[40],"[(1, 39)]"